### ISSUE TITLE
Handling nan and inf values

### ISSUE THREAD

**Issue by rocky** [zrax/pycdc#136]
```
a = 1e300 * 1e300 * 0
b = -1e300 * 1e300 * 0
c = 1e300 * 1e300
d = -1e300 * 1e300
```

gives:

```
a = nan
b = nan
c = inf
d = -inf
```

but Python doesn't allow these in source code to represent their internal values. 

uncompyle6 uses float('nan'), etc. although there are numerous other ways to handle.

**Comment by dotjrich** [comment]
Hello! I've been taking a stab at this issue and have a change that produces the proper decompiled output. It takes the `float()` approach mentioned by @rocky. I'm now looking into adding a few tests for it.

I did have a question regarding the output of `pycdas`. From my testing, I've noticed that that constants that are printed out differ between Python 2 and 3. In particular, Python 2 seems to include both the nan/inf values + the numeric constants.

**Python 2.7.18**
```
[Constants]
    1e+300
    0
    -1e+300
    None
    inf
    -nan
    -inf
    -nan
    inf
    -inf
```

**Python 3.8.5**
```
[Constants]
    -nan
    -nan
    inf
    -inf
    None
```

I'm still very much a noob when it comes to Python internals, so I was wondering if this difference was expected. If not, is this something that should be tackled as part of this issue?

**Comment by zrax** [comment]
The fact that the (unused) constants are stored in the bytecode for Python 2.7 and not 3.8 is probably due to an optimization that happened sometime after 2.7.  In other words, it's the Python compiler that decides whether or not to put those in the constant list, not pycdc/pycdas.  As long as they're not used by the disassembly, it shouldn't matter whether they're there or not.

**Comment by dotjrich** [comment]
That makes sense, thank you for the explanation! I have tests ready and passing, so I'll be opening up a PR soon.
