### ISSUE TITLE
Unsupported opcode: LOAD_METHOD on Python 3.7 files

### ISSUE THREAD

**Issue by KhArtNJava** [zrax/pycdc#163]
Hello.
I am using pycdc, cloned it from mater branch and compiled from scratch today.
When I am trying to decompile Python 3.7 files, pycdc failed to decompile it fully.

    Unsupported opcode: LOAD_METHOD
    *********************** (here a part of file, that pycdc is able to decompile)
    # WARNING: Decompyle incomplete

The file, that I am trying to decompile: 
[d.zip](https://github.com/zrax/pycdc/files/2452424/sim_info.zip)

Can you take a look at this file, please?

**Comment by zrax** [comment]
LOAD_METHOD and CALL_METHOD are opcodes added in Python 3.7.  Unfortunately, I haven't had time to do much more than support the bytecode (for pycdas) for 3.7 yet, so it's unsurprising that it doesn't work yet.

**Comment by mancoast** [comment]
Greetings,

I can take a look time permitting. Any pointers/thoughts towards implementation?

Thanks,
Coast

**Comment by KhArtNJava** [comment]
@zrax Michael, can you spend some of your time for it, please? )

**Comment by rocky** [comment]
@mancoast The first place to start would be the Python spec for [LOAD_METHOD](https://python.readthedocs.io/en/latest/library/dis.html?highlight=LOAD_METHOD#opcode-LOAD_METHOD). And below that is `CALL_METHOD`. 

If I recall correctly  a `LOAD_METHOD` originated in Pypy, so having these work would also go a long way (I think) to supporting Pypy as well.

**Comment by CaptSolo** [comment]
I am getting the same error message (as reported by @KhArtNJava ) when running pycdc on Python 3.8 .pyc files:
```
Unsupported opcode: LOAD_METHOD
[...]
# WARNING: Decompyle incomplete
```

P.S. thanks for a great tool! :) - even though pycdc could not fully disassemble original Python code, `pycdas` showed decompiled bytecode that was sufficient for the task at hand

**Comment by coast77777777777** [comment]
Reference how Load_Build_Class was added: https://github.com/zrax/pycdc/commit/58edafd872de193b52c3079117ab04db4b18d781

LOAD_METHOD(namei)
Loads a method named co_names[namei] from TOS object. TOS is popped and method and TOS are pushed when interpreter can call unbound method directly. TOS will be used as the first argument (self) by CALL_METHOD. Otherwise, NULL and method is pushed (method is bound method or something else).

New in version 3.7.

CALL_METHOD(argc)
Calls a method. argc is number of positional arguments. Keyword arguments are not supported. This opcode is designed to be used with LOAD_METHOD. Positional arguments are on top of the stack. Below them, two items described in LOAD_METHOD on the stack. All of them are popped and return value is pushed.

New in version 3.7.

**Comment by retsyo** [comment]
well, any processing?

**Comment by will2022** [comment]
I've just got the same error

**Comment by lameventanas** [comment]
Same here, it would be great if this opcode was implemented.

**Comment by lameventanas** [comment]
In case anyone wants to implement it, [this](https://github.com/python/cpython/commit/f2392133eba777f05947a8996c507690b95379c3) is the commit that added LOAD_METHOD and CALL_METHOD.

**Comment by K4zBeK** [comment]
please someone add LOAD_METHOD into python 3.8 opcodes

**Comment by dimonpanik** [comment]
These opcodes have already been added as I see, but with _A.
