### ISSUE TITLE
Python 3.6+ SETUP_ANNOTATION 

### ISSUE THREAD

**Issue by rocky** [zrax/pycdc#169]
Python 3.6+ `SETUP_ANNOTATION` is not handled. Here is code that will create such an opcode:

```pythion
x: int
```

**Comment by dotjrich** [comment]
I've started noodling around with this one and wanted to talk about my strategy and see if it makes sense.

From what I can tell, it looks like we'll see `SETUP_ANNOTATIONS` on the stack if an annotation is used anywhere (from my testing, it looks like it's always the first thing on the top).

When a variable has been annotated, we'll then see something along the lines of this:
```
         0      LOAD_NAME               1: int
        12      LOAD_NAME               2: __annotations__
        14      LOAD_CONST              2: 'x'
```

So, what I was planning on doing is set some kind of flag if we find `SETUP_ANNOTATIONS`. Then, if that flag is set, we'll take a peek at the top of the stack whenever we encounter `LOAD_CONST` and see if we find `__annotations__`. If we do, we'll process it as an annotation accordingly.

Does that sound like a viable strategy?

**Comment by zrax** [comment]
If you look a little more closely, it looks like what the code actually does is translate:

```python
x: int
```
into
```python
__annotations__['x'] = int
```

So the lazy solution would just be to ignore `SETUP_ANNOTATIONS`, and leave the code the compiler translated as-is...  But the more advanced solution might be to look for subscript stores to `__annotations__` and emit the appropriate annotation instead.

NOTE: This gets a little trickier with mixed annotation and assignment, since Python turns this into two statements:

```python
x: int = 5

### Compiles to:
x = 5
__annotations__['x'] = int
```

**Comment by dotjrich** [comment]
Thank you for the pointers; this is very helpful! I'll see what I can come up with.
