### ISSUE TITLE
good afternoon, sir.

### ISSUE THREAD

**Issue by adilem** [zrax/pycdc#176]
Hello. master

Can you look at these files? I can't decompile them.

please, can you help me
[Desktop.zip](https://github.com/zrax/pycdc/files/5393251/Desktop.zip)

Thank you!

**Comment by zrax** [comment]
I haven't looked at these files, but they look large (and likely a complete piece of code, rather than a minimal example).  Unfortunately, that's not really useful for reporting bugs; it would be much better to identify the bug(s) with a minimal example, or comment on existing open bugs if appropriate.
