### ISSUE TITLE
Unsupported opcode: JUMP_IF_NOT_EXC_MATCH

### ISSUE THREAD

**Issue by NiKoCZ89** [zrax/pycdc#242]
Unsupported opcode: JUMP_IF_NOT_EXC_MATCH

any fix/update?

**Comment by abros1** [comment]
Same issue with me

**Comment by karjok** [comment]
I also had a similar error last night, when I tried to decompile the pyc file compiled with python 3.10, the message "Unsupported opcode: BLA_BLA_BLA" appears.



I think this is an error because the pyc file that will be decoded is a bytecode file compiled with python 3.9 and above, and the opcodes that are not supported by pycdc are opcodes that just appeared in python version 3.9 and above.

so I tried reading the ASTree.cpp file and studying it, then I realized that the opcode that was printed as an error was not in the "case block" of the ASTree.cpp file.

I tried to change it a little by adding the opcodes printed in the error message into the case block (on line 1166)
```cpp
case Pyc::JUMP_IF_NOT_EXC_MATCH_A:
case Pyc::RERAISE_A:
```
then rebuild it. I don't know what happened but it solved my problem when trying to decompile python 3.9 and above bytecode. everything is done!

**Comment by angelheart150** [comment]
i have the same error , how can i solve it ?

![photo_2022-09-22_20-48-57](https://user-images.githubusercontent.com/67199651/191858264-8d542c3c-50a9-481e-bd11-186bb6886e29.jpg)

![photo_2022-09-22_20-48-57 (2)](https://user-images.githubusercontent.com/67199651/191858271-2312a1a2-10bb-475b-a774-ed0ba5626512.jpg)

**Comment by AngeloD2022** [comment]
[obfuscated_stealer.pyc.zip](https://github.com/zrax/pycdc/files/10889531/obfuscated_stealer.pyc.zip)

I am trying to analyze malware, and I received this error when putting the above file into pycdc.

**Comment by sami-soft** [comment]
Same issue with me

**Comment by fernando535** [comment]
Same issue... how can i resolved it?

**Comment by kzorin52** [comment]
same

**Comment by meir555** [comment]
Temporary fix:
I tried to comment out the line `return new ASTNodeList(defblock->nodes());`  in ASTree.cpp (this is the line that stops when it reaches an unknown opcode, in the `default:`)
The output is not completely correct, I had places where the try-catch was not in place, but all the decompiled code is readable, and after minor corrections it worked perfectly.

**Comment by zrax** [comment]
Duplicate #450
