### ISSUE TITLE
#Decompyle incomplete - Python 3.9 please help

### ISSUE THREAD

**Issue by Flexium80** [zrax/pycdc#253]
#Decompyle incomplete on terminal python 3.9
Unsupported opcode: RERAISE

**Comment by Ahmed7fathi** [comment]
I hope someone solves this there is no decompile tool that can decompile python 3.9 yet

**Comment by karjok** [comment]
I also had a similar error last night, when I tried to decompile the pyc file compiled with python 3.10, the message "Unsupported opcode: BLA_BLA_BLA" appears.



I think this is an error because the pyc file that will be decoded is a bytecode file compiled with python 3.9 and above, and the opcodes that are not supported by pycdc are opcodes that just appeared in python version 3.9 and above.

so I tried reading the ASTree.cpp file and studying it, then I realized that the opcode that was printed as an error was not in the "case block" of the ASTree.cpp file.

I tried to change it a little by adding the opcodes printed in the error message into the case block (on line 1166)
```cpp
case Pyc::JUMP_IF_NOT_EXC_MATCH_A:
case Pyc::RERAISE_A:
```
then rebuild it. I don't know what happened but it solved my problem when trying to decompile python 3.9 and above bytecode. everything is done!

**Comment by canglanyue** [comment]
> I also had a similar error last night, when I tried to decompile the pyc file compiled with python 3.10, the message "Unsupported opcode: BLA_BLA_BLA" appears.
> 
> I think this is an error because the pyc file that will be decoded is a bytecode file compiled with python 3.9 and above, and the opcodes that are not supported by pycdc are opcodes that just appeared in python version 3.9 and above.
> 
> so I tried reading the ASTree.cpp file and studying it, then I realized that the opcode that was printed as an error was not in the "case block" of the ASTree.cpp file.
> 
> I tried to change it a little by adding the opcodes printed in the error message into the case block (on line 1166)
> 
> ```c++
> case Pyc::JUMP_IF_NOT_EXC_MATCH_A:
> case Pyc::RERAISE_A:
> ```
> 
> then rebuild it. I don't know what happened but it solved my problem when trying to decompile python 3.9 and above bytecode. everything is done!

after rebuild,Try to decompile, the program reports an error
![image](https://user-images.githubusercontent.com/75410383/173406905-d63657c5-855a-4b42-b57c-53497b9d8a75.png)

**Comment by zrax** [comment]
Duplicate #450

**Comment by raymondren1982** [comment]
yes,it work, I change ASTree.cpp(1158line) as following:
        case Pyc::JUMP_IF_FALSE_A:
        case Pyc::JUMP_IF_TRUE_A:
        case Pyc::JUMP_IF_FALSE_OR_POP_A:
        case Pyc::JUMP_IF_TRUE_OR_POP_A:
        case Pyc::POP_JUMP_IF_FALSE_A:
        case Pyc::POP_JUMP_IF_TRUE_A:
        case Pyc::POP_JUMP_FORWARD_IF_FALSE_A:
        case Pyc::POP_JUMP_FORWARD_IF_TRUE_A:
        case Pyc::INSTRUMENTED_POP_JUMP_IF_FALSE_A:
        case Pyc::INSTRUMENTED_POP_JUMP_IF_TRUE_A:
        case Pyc::RERAISE:                    //raymond ren
        case Pyc::CALL_FUNCTION_EX_A:
        case Pyc::JUMP_IF_NOT_EXC_MATCH_A:
            {
                PycRef<ASTNode> cond = stack.top();
                PycRef<ASTCondBlock> ifblk;
                int popped = ASTCondBlock::UNINITED;
