### ISSUE TITLE
Unsupported opcodes JUMP_IF_NOT_EXC_MATCH and  DICT_MERGE

### ISSUE THREAD

**Issue by gygabrain** [zrax/pycdc#258]
Should we expect support for opcodes JUMP_IF_NOT_EXC_MATCH and DICT_MERGE in the near future?

**Comment by karjok** [comment]
I also had a similar error last night, when I tried to decompile the pyc file compiled with python 3.10, the message "Unsupported opcode: BLA_BLA_BLA" appears.

I think this is an error because the pyc file that will be decoded is a bytecode file compiled with python 3.9 and above, and the opcodes that are not supported by pycdc are opcodes that just appeared in python version 3.9 and above.

so I tried reading the ASTree.cpp file and studying it, then I realized that the opcode that was printed as an error was not in the "case block" of the ASTree.cpp file.

I tried to change it a little by adding the opcodes printed in the error message into the case block (on line 1166)

case Pyc::JUMP_IF_NOT_EXC_MATCH_A:
case Pyc::RERAISE_A:

then rebuild it. I don't know what happened but it solved my problem when trying to decompile python 3.9 and above bytecode. everything is done!

**Comment by Woopertail** [comment]
@karjok wow, i have to try it!

**Comment by fishANDdog** [comment]
I have change the ASTree.cpp file as above, eg. add `case Pyc::JUMP_IF_NOT_EXC_MATCH_A: `and `case Pyc::RERAISE_A:`. But I get the error message "Unsupported opcode: RERAISE".  What can I do?  If you know why, please notify me,  thanks. @karjok

**Comment by nicolasvijalba** [comment]
I change the  ASTree.cpp but still get the error Unsupported opcode: JUMP_IF_NOT_EXC_MATCH, do you have the a sample file? @karjok, thanks for the help that you can give me

**Comment by nicolasvijalba** [comment]
I have a new error, after advance with the code of ASTree, i get:

# Source Generated with Decompyle++
# File: conversorexcelZP.pyc (Python 3.9)

Segmentation fault

Any recommendation?

**Comment by kursatturkay** [comment]
Unsupported opcode: RERAISE

**Comment by zrax** [comment]
Duplicate #450
