### ISSUE TITLE
[bug]pycdc decode python3.8 exception handling fail！

### ISSUE THREAD

**Issue by longxinyun-security** [zrax/pycdc#260]
![image](https://user-images.githubusercontent.com/70429515/167600807-b1707da9-62d3-475b-9b29-a4118143ce33.png)

PycRef<ASTNode> res = value.cast<ASTCall>()->pparams().front();

value.cast<ASTCall>()->pparams().size()==0

stack = stack_hist.top();
stack.pop();

stack_hist.size()==0

**Comment by karjok** [comment]
I also had a similar error last night, when I tried to decompile the pyc file compiled with python 3.10, the message "Unsupported opcode: BLA_BLA_BLA" appears.



I think this is an error because the pyc file that will be decoded is a bytecode file compiled with python 3.9 and above, and the opcodes that are not supported by pycdc are opcodes that just appeared in python version 3.9 and above.

so I tried reading the ASTree.cpp file and studying it, then I realized that the opcode that was printed as an error was not in the "case block" of the ASTree.cpp file.

I tried to change it a little by adding the opcodes printed in the error message into the case block (on line 1166)
```cpp
case Pyc::JUMP_IF_NOT_EXC_MATCH_A:
case Pyc::RERAISE_A:
```
then rebuild it. I don't know what happened but it solved my problem when trying to decompile python 3.9 and above bytecode. everything is done!

**Comment by longxinyun-security** [comment]
> I also had a similar error last night, when I tried to decompile the pyc file compiled with python 3.10, the message "Unsupported opcode: BLA_BLA_BLA" appears.
> 
> I think this is an error because the pyc file that will be decoded is a bytecode file compiled with python 3.9 and above, and the opcodes that are not supported by pycdc are opcodes that just appeared in python version 3.9 and above.
> 
> so I tried reading the ASTree.cpp file and studying it, then I realized that the opcode that was printed as an error was not in the "case block" of the ASTree.cpp file.
> 
> I tried to change it a little by adding the opcodes printed in the error message into the case block (on line 1166)
> 
> ```c++
> case Pyc::JUMP_IF_NOT_EXC_MATCH_A:
> case Pyc::RERAISE_A:
> ```
> 
> then rebuild it. I don't know what happened but it solved my problem when trying to decompile python 3.9 and above bytecode. everything is done!

Thanks, bro !

**Comment by karjok** [comment]
just add the unsupported opcode to the case block in the ASTree.cpp file as above. hope it helps :)
Thanks for replying.

**Comment by rrblgn** [comment]
> I also had a similar error last night, when I tried to decompile the pyc file compiled with python 3.10, the message "Unsupported opcode: BLA_BLA_BLA" appears.
> 
> I think this is an error because the pyc file that will be decoded is a bytecode file compiled with python 3.9 and above, and the opcodes that are not supported by pycdc are opcodes that just appeared in python version 3.9 and above.
> 
> so I tried reading the ASTree.cpp file and studying it, then I realized that the opcode that was printed as an error was not in the "case block" of the ASTree.cpp file.
> 
> I tried to change it a little by adding the opcodes printed in the error message into the case block (on line 1166)
> 
> ```c++
> case Pyc::JUMP_IF_NOT_EXC_MATCH_A:
> case Pyc::RERAISE_A:
> ```
> 
> then rebuild it. I don't know what happened but it solved my problem when trying to decompile python 3.9 and above bytecode. everything is done!

Could you elaborate on adding those cases to the corresponding line? I inserted the lines you shared but still cannot decode try/except blocks

**Comment by longxinyun-security** [comment]
Python CFG recognition is a labor-intensive task, and many instructions in new versions are not supported by pycdc, requiring the addition of a large amount of code and testing in ASTree.cpp. The "Unsupported opcode" error is issued in the BuildFromCode function and needs to be fixed in the switch/case of this function. My translation was generated by an AI as my English is not very good.

**Comment by zrax** [comment]
Duplicate #449
