### ISSUE TITLE
python3.11 compatibility

### ISSUE THREAD

**Issue by ArtherLogic** [zrax/pycdc#328]
When we compatible python 3.11, pycdc can not word as well in this version.
Thanks

**Comment by TheHellTower** [comment]
> When we compatible python 3.11, pycdc can not word as well in this version. Thanks

Hello, the only advice I could give you is to be patient and if possible you can contribute by sending scripts samples(compiled or no) using the not supported yet opcodes for the 3.11.

Don't send any automation script or stuff like this it has to be a very simple script that will use the wanted and targeted opcodes.

Regards.

**Comment by 0xMalFunc** [comment]
Hi @TheHellTower,

I wanted to drop in and say thank you for your work on the pycdc project and for taking on the task of adding compatibility for Python 3.11. It's great to see developers like you contributing to open source projects and making them better for the community.

I understand that there are some issues with pycdc in Python 3.11, but I'm confident that with your expertise and efforts, these issues will be resolved soon. As you know, there are many use cases for pycdc, and the community is eagerly waiting for its compatibility with the latest version of Python.

In case you need any additional resources or support for your work, please do let us know. Also, if there are any funding needs to expedite the development process, I encourage you to run a funding round as the community would be happy to support you.

Once again, thank you for your contributions to the project, and I'm looking forward to the upcoming improvements.

Best regards.

**Comment by TheHellTower** [comment]
> Hi @TheHellTower,
> 
> I wanted to drop in and say thank you for your work on the pycdc project and for taking on the task of adding compatibility for Python 3.11. It's great to see developers like you contributing to open source projects and making them better for the community.
> 
> I understand that there are some issues with pycdc in Python 3.11, but I'm confident that with your expertise and efforts, these issues will be resolved soon. As you know, there are many use cases for pycdc, and the community is eagerly waiting for its compatibility with the latest version of Python.
> 
> In case you need any additional resources or support for your work, please do let us know. Also, if there are any funding needs to expedite the development process, I encourage you to run a funding round as the community would be happy to support you.
> 
> Once again, thank you for your contributions to the project, and I'm looking forward to the upcoming improvements.
> 
> Best regards.

Hi, 

I'm moving in a few days so I might not be able to work a lot on pycdc since I have no warranty to get a WiFi connection fast but I try my best to be available.

Obviously maintaining a project like pycdc is not easy and I'm far away to be a expart I miss some info to update correctly all the pycdc parts, I might only be able to add opcodes support if I decided to fork this project one day.

Yeah if you are rich don't hesitate to send me money it would be helpful and give motivation 😎 because I'm sometime lost in pycdc code due to my innexistence since the beginning of the project and I'm not a expert about the Python runtime for example I'm trying to learn some things about the other parts and see how I could update it if I fork it since zrax only merge PR and don't really work on it anymore.. I feel like it's sad because I would like to continue to contribute to it with him continuing too but I understand him it's really hard to provide such advanced utilities and update them for everyone to be happy but this would be a very massive work for me too and I'm sure not a lot of people would be ready to support with money I got a lot of malicious dm recently to get decompiled scripts and for free obviously while it can take me time to update something since I kinda have a life next to it😂

No problem as soon as I'm in a stable situation(a place to stay) I will see to commit myself more on it and if really needed fork pycdc because I personally like this project and I think I could get some benefits from it, for example I learned things while trying to update it that I might never have known without it. 😄

Best Regards,
TheHellTower.

**Comment by TheHellTower** [comment]
Test

**Comment by TheHellTower** [comment]
> 0xMalFunc

Hi @0xMalFunc,

After some verifications I might be available maximum a week after the land, sadly not having an incredible phone(Other poor people will understand me ! 😄) plan I can't warranty to publish soon or it would be to fix multiple opcodes that could take some time, I don't have a date for a stable WiFi plan so I can't give a better answer for availability as of today.

The only thing I can assure right now is that if pycdc stay unmaintained until the 5 May, I may fork it and update it myself when I will have updates to provide.

Anyway if you have suggestions for pycdc that are not about a unsupported opcode, a question or anything else you would like to discute in private you can either click on me to see my social links or feel free to email me at the email above.

Best Regards,
TheHellTower.

**Comment by zrax** [comment]
Duplicate #452
