### ISSUE TITLE
Unsupported opcode:PUSH_NULL PRECALL

### ISSUE THREAD

**Issue by JZZLQ** [zrax/pycdc#382]
pycdc.exe main.pyc -o main.py
Unsupported opcode: PUSH_NULL

Script main.pyc：
[https://tria.ge/samples/230904-g1bdlaef38/sample.zip](url)

pycdc.exe b.pyc -o b.py
Unsupported opcode: PRECALL

Script b.pyc：
[https://tria.ge/samples/230904-gyxh2sef34/sample.zip](url)

**Comment by TheHellTower** [comment]
> pycdc.exe main.pyc -o main.py Unsupported opcode: PUSH_NULL
> 
> Script main.pyc： [https://tria.ge/samples/230904-g1bdlaef38/sample.zip](url)
> 
> pycdc.exe b.pyc -o b.py Unsupported opcode: PRECALL
> 
> Script b.pyc： [https://tria.ge/samples/230904-gyxh2sef34/sample.zip](url)

Hello,

These problem already been fixed [here](https://github.com/zrax/pycdc/pull/324) I believe you didn't compile the last version of pycdc..
Please try using the last version of pycdc, I personally publish [built up-to-date pycdc & pycdas](https://github.com/TheHellTower/decompyle-builds/releases/tag/build-21-Aug-2023-f5c1d42).

If it fix your issue don't forget to close this issue otherwise kindly return the error/problem happening.

Best Regards.
